name: Generate sitemap
on:
  push:
    branches:
      - $default-branch
    paths:
      - "**.html"
  pull_request:
    branches:
      - $default-branch

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1.9.1
        with:
          base-url-path: https://slamthedragon.me/

      - name: Output stats
        run: |
          echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
          echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
          echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

      - name: Commit and push
        run: |
          if [[ `git status --porcelain sitemap.xml` ]]; then
            git add sitemap.xml
            git commit -m "Automated sitemap update" sitemap.xml
            git push
          fi
